### ISSUE TITLE
Templates folder "layout" was not found

### ISSUE THREAD

**Issue by chris-peng-1244** [dragonmantank/dockerfordevs-app#1]
While I was reading your wonderful book "Docker for developers" and trying this example, I encountered a fatal error.

> fatal error: Uncaught exception 'LogicException' with message 'The template folder "layout" was not found.' in /var/www/vendor/league/plates/src/Template/Folders.php:60

 After a little research, I found out a solution
1. add **templates/layout** folder, add **default.phtml** file
2. add `'layout' => [ 'templates/layout' ]` after line 17 of config/autoload/templates.global.php

Is it possible that you forget to add the layout file to the project? If it is not the case, please inform me where I get it wrong, thanks.

**Comment by ajfranzoia** [comment]
I'm having the same issue as @chris-peng-1244, the layout file might be missing.

**Comment by dragonmantank** [comment]
The layout folder was never added as the root path `/` was never meant to be used, just the api route. This wasn't originally a problem.

Looks like that has changed, so I corrected this in a6ccf4d1484b93a4801ed86280aa921175cae3b1
