### ISSUE TITLE
Docker Novice

### ISSUE THREAD

**Issue by mikeerickson** [dragonmantank/dockerfordevs-app#2]
Hey @dragonmantank 

Curious, what would be required to have this starter project use php7 instead of php56?

**Comment by dragonmantank** [comment]
Hi Mike!

In the next revision of the book I'll be updating it to 7.1, but really all you should have to do now is change any references to php:5.6-* to php:7-* ... in any instances where I'm just using php:cli or php:fpm, those should just need fresh pulls to download the newest versions (which should be 7.1 according to Docker Hub).

**Comment by mikeerickson** [comment]
@dragonmantank Thx for reply, I will give your suggestion a whirl.
